### ISSUE TITLE
Project Management - Project Charter

### ISSUE THREAD

**Issue by lespabrandzulic82** [alptium/football#3]

**Comment by lespabrandzulic82** [comment]
@valentinacupac , I have finished Project Charter. I found template on link:
https://webcache.googleusercontent.com/search?q=cache:WlaajBOFclUJ:https://www2a.cdc.gov/cdcup/library/templates/CDC_UP_Project_Charter_Template.doc+&cd=2&hl=sr&ct=clnk&gl=rs&client=firefox-b-ab

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, please format timelines, milestones and roles as table. Google GitHub Markdown tables.

**Comment by lespabrandzulic82** [comment]
@valentinacupac , I have formatted this.

**Comment by valentinajemuovic** [comment]
@lespabrandzulic82, correct.
